#!/usr/bin/env python3
"""Recipe #49 - Render a PR-comment-friendly summary of channel/transformer changes.

For every changed *.xml between two git refs, produce a markdown block
listing transformer script diffs (line counts, function signatures changed)
and connector-level metadata changes. Designed to be posted back to the PR.

Author: Nirmitee.io | License: MIT
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

from lxml import etree


def git(*args: str) -> str:
    return subprocess.check_output(["git", *args], text=True)


def changed_xml_files(base: str, head: str) -> list[str]:
    out = git("diff", "--name-only", base, head)
    return [
        line for line in out.splitlines()
        if line.endswith(".xml") and line.split("/")[0] in
        {"channels", "transformers", "code-templates"}
    ]


def load_xml_at_ref(ref: str, path: str):
    try:
        blob = subprocess.check_output(["git", "show", f"{ref}:{path}"])
    except subprocess.CalledProcessError:
        return None
    try:
        return etree.fromstring(blob)
    except etree.XMLSyntaxError:
        return None


def summarize_channel(root) -> dict:
    if root is None:
        return {}
    return {
        "name": (root.findtext("name") or "").strip(),
        "id": (root.findtext("id") or "").strip(),
        "enabled": (root.findtext("enabled") or "").strip(),
        "source": (root.findtext("sourceConnector/transportName") or "").strip(),
        "destinations": [
            (c.findtext("transportName") or "").strip()
            for c in root.findall("destinationConnectors/connector")
        ],
        "transformer_lines": sum(
            len((s.text or "").splitlines())
            for s in root.iter("script")
        ),
    }


def render(path: str, before: dict, after: dict) -> str:
    if not before and after:
        return f"### `{path}` — NEW\n- Source: `{after.get('source', '?')}`\n- Destinations: {after.get('destinations', [])}\n- Transformer lines: {after.get('transformer_lines', 0)}\n"
    if before and not after:
        return f"### `{path}` — DELETED\n- Was: `{before.get('name', '?')}` ({before.get('source', '?')})\n"

    lines = [f"### `{path}`"]
    name_b, name_a = before.get("name"), after.get("name")
    if name_b != name_a:
        lines.append(f"- Name: `{name_b}` → `{name_a}`")
    if before.get("source") != after.get("source"):
        lines.append(f"- Source transport: `{before.get('source')}` → `{after.get('source')}`")
    if before.get("destinations") != after.get("destinations"):
        lines.append(f"- Destinations: `{before.get('destinations')}` → `{after.get('destinations')}`")
    if before.get("enabled") != after.get("enabled"):
        lines.append(f"- Enabled: `{before.get('enabled')}` → `{after.get('enabled')}`")
    delta = after.get("transformer_lines", 0) - before.get("transformer_lines", 0)
    if delta != 0:
        sign = "+" if delta > 0 else ""
        lines.append(f"- Transformer JS: {sign}{delta} lines (was {before.get('transformer_lines', 0)}, now {after.get('transformer_lines', 0)})")
    if len(lines) == 1:
        lines.append("- _(no structural change; whitespace or comment edits only)_")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--base", required=True, help="base git ref (e.g. PR base SHA)")
    ap.add_argument("--head", required=True, help="head git ref (e.g. PR head SHA)")
    ap.add_argument("--out", default="diff-summary.md")
    args = ap.parse_args()

    files = changed_xml_files(args.base, args.head)

    parts = ["## Mirth channel changes\n"]
    if not files:
        parts.append("_No channel / transformer / code-template XML files changed._\n")
    else:
        parts.append(f"_Detected {len(files)} changed file(s)._\n")
        for path in files:
            before = summarize_channel(load_xml_at_ref(args.base, path))
            after = summarize_channel(load_xml_at_ref(args.head, path))
            parts.append(render(path, before, after))

    parts.append("\n---\n_Generated by recipe #49 channel CI._")

    Path(args.out).write_text("\n".join(parts))
    print("\n".join(parts))
    return 0


if __name__ == "__main__":
    sys.exit(main())
